DB2LimitedTask/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^accounts/', include('users.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^post/(?P<pk>[-\d]+)/$', login_required(views.PostDetailView.as_view()), name="post_detail"),
    url(r'^post/(?P<pk>[-\d]+)/add_comment/$', login_required(views.AjaxCreateCommentFormView.as_view()), name="add_comment"),
    url(r'^post_create/$', login_required(views.CreatePostFormView.as_view()), name="post_create"),
    url(r'^toggle_like/(?P<pk>[-\d]+)/$', login_required(views.toggle_like), name="toggle_like")
]

blog/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()


class Post(models.Model):
    title = models.CharField(_('Title'), max_length=256)
    preview_text = models.TextField(_('Preview text'), max_length=300, blank=True, null=True)
    main_image = models.ImageField(_('Main image'), upload_to='post')
    body = models.TextField(_('Body'))
    author = models.ForeignKey(
        User,
        related_name='posts',
        verbose_name=_('Author')
    )

    date_created = models.DateTimeField(_('Date created'), auto_now_add=True)
    date_modified = models.DateTimeField(_('Date modified'), auto_now=True)

    class Meta:
        ordering = ('-date_created', )

    def __str__(self):
        return self.title

    def get_preview_text(self):
        return self.preview_text if self.preview_text else self.body[:300]+'...'

    def user_like_exist(self, user):
        return self.likes.filter(user=user).count() > 0

    @property
    def likes_count(self):
        return self.likes.count()

    @property
    def comments_count(self):
        return self.comments.count()

    @models.permalink
    def get_absolute_url(self):
        return "blog:post_detail", (self.id, )


class Comment(models.Model):
    author = models.ForeignKey(
        User,
        related_name='comments',
        verbose_name=_('Author')
    )
    post = models.ForeignKey(
        Post,
        related_name='comments',
        verbose_name=_('Post')
    )
    body = models.TextField(_('Body'))

    date_created = models.DateTimeField(_('Date created'), auto_now_add=True)

    def __str__(self):
        return "Comment %s by %s" %(self.post.title, self.author.email)

    class Meta:
        ordering = ('-date_created', )


class Like(models.Model):
    user = models.ForeignKey(
        User,
        related_name='likes',
        verbose_name=_('User')
    )
    post = models.ForeignKey(
        Post,
        related_name='likes',
        verbose_name=_('Post')
    )

    date_created = models.DateTimeField(_('Date created'), auto_now_add=True)

    class Meta:
        unique_together = ('user', 'post')
        ordering = ('-date_created',)

blog/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.db.models import Q

from .models import Post, Comment

class PostSearchForm(forms.Form):
    country = forms.CharField(widget=forms.TextInput(attrs={"placeholder": _('Country')}), required=False)
    city = forms.CharField(widget=forms.TextInput(attrs={"placeholder": _('City')}), required=False)
    keyword = forms.CharField(widget=forms.TextInput(attrs={"placeholder": _('Search text')}), required=False)

    def search(self, base_qs=None):
        posts = base_qs if base_qs else Post.objects.all()
        print(posts)
        if self.is_valid():
            if self.cleaned_data.get("country"):
                posts = posts.filter(author__country__iexact=self.cleaned_data['country'])

            if self.cleaned_data.get("city"):
                posts = posts.filter(author__city__iexact=self.cleaned_data['city'])

            if self.cleaned_data.get("keyword"):
                kw = self.cleaned_data['keyword']
                posts = posts.filter(Q(title__icontains=kw) | Q(preview_text__icontains=kw) | Q(body__icontains=kw))

        return posts.prefetch_related('likes', 'comments')


class CreatePostForm(forms.ModelForm):

    class Meta:
        model = Post
        exclude = ('author', )


class CreateCommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('body', )

blog/views.py
from django.views.generic import DetailView, FormView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404, redirect
from django.http import JsonResponse

from .models import Post, Comment
from .forms import CreateCommentForm, CreatePostForm
# Create your views here.


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'
    comment_paginte_by = 10

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        page = self.request.GET.get('page', 1)

        paginator = Paginator(self.object.comments.all(), self.comment_paginte_by)

        try:
            comments = paginator.page(page)
        except PageNotAnInteger:
            comments = paginator.page(1)
        except EmptyPage:
            comments = paginator.page(paginator.num_pages)

        ctx['comments'] = comments
        ctx['comment_form'] = CreateCommentForm
        return ctx


class AjaxCreateCommentFormView(FormView):
    model = Comment
    form_class = CreateCommentForm

    def get(self, request, *args, **kwargs):
        self.post = get_object_or_404(Post, pk=kwargs.get('pk'))
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.post = get_object_or_404(Post, pk=kwargs.get('pk'))
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = self.post
        comment.author = self.request.user
        comment.save()

        return JsonResponse({'status': 'ok', 'redirect_url': self.post.get_absolute_url()})

    def form_invalid(self, form):
        return JsonResponse({'status': 'error', 'errors': form.errors})


class CreatePostFormView(FormView):
    form_class = CreatePostForm
    template_name = 'blog/post_create.html'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()

        return redirect(post.get_absolute_url())


def toggle_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if not post.user_like_exist(request.user):
        post.likes.create(user=request.user)
        liked=True
    else:
        post.likes.filter(user=request.user).delete()
        liked=False

    return JsonResponse({'likes_count':post.likes.count(), 'status': 'ok', 'liked':liked})

templates/blog/post_create.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}{{ block.super }} - Post creation{% endblock %}

{% block content %}
    <h2 class="align-center">Post creation</h2>
    <div class="col-md-6 col-md-offset-3 col-xs-12">
    <form method="post" enctype="multipart/form-data">
        <p>{% for error in form.none_field_errors  %}{{ error }} {% endfor %}</p>
        {% for field in form %}
            <div class="form-group {% if field.errors %}has-warning{% endif %}">
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
                {% if field.errors %}
                    <span class="help-block">{{ field.errors }}</span>
                {% endif %}
            </div>
        {% endfor %}
        {% csrf_token %}
        <input class="btn btn-primary" type="submit" value="Create">
    </form>
    </div>
{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}

{% load thumbnail widget_tweaks likes_tags %}

{% block title %}{{ block.super }} - {{ post.title }}{% endblock %}


{% block content %}
        <hr>
        <h6>{{ post.date_created }}</h6>
        <h1>{{ post.title }}</h1>
        <div>
        {% thumbnail post.main_image "500" crop="center" as img %}
            <img src="{{ img.url }}" alt="{{ post.title }}">
        {% endthumbnail %}
        </div>
        <br>
        <p style="font-size: 18px;">
            {% include 'blog/partials/post_like.html' %}
        </p>
        <p>{{ post.body }}</p>
        <hr>
        <h3>Comments</h3>
        <form class="form" action="{% url 'blog:add_comment' post.pk %}" id="comment-form" method="post" >
            {% csrf_token %}
            {% for field in comment_form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {% render_field field class="form-control" %}
                </div>
            {% endfor %}
            <input type="submit" class="btn btn-primary" value="add comment">
        </form>
        <div>
        {% for comment in comments %}
            <div class="panel panel-default">
                <div class="panel-heading"><span>{{ comment.author.email }}</span> <span style="float: right" class="text-right">{{ comment.date_created }}</span></div>
                <div class="panel-body">
                    {{ comment.body }}
                </div>
            </div>
        {% endfor %}
        </div>
    {% include 'partials/pagination.html' with page_obj=comments paginator=comments.paginator %}

{% endblock %}