DB2LimitedTask/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^accounts/', include('users.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^post/(?P<pk>[-\d]+)/$', login_required(views.PostDetailView.as_view()), name="post_detail"),
    url(r'^post/(?P<pk>[-\d]+)/add_comment/$', login_required(views.AjaxCreateCommentFormView.as_view()), name="add_comment"),
    url(r'^post_create/$', login_required(views.CreatePostFormView.as_view()), name="post_create"),
    url(r'^toggle_like/(?P<pk>[-\d]+)/$', login_required(views.toggle_like), name="toggle_like")
]

main/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^$', login_required(views.MainView.as_view()), name='main'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.views.generic import ListView

from blog.models import Post
from blog.forms import PostSearchForm
# Create your views here.


class MainView(ListView):
    model = Post
    paginate_by = 3
    template_name = 'main.html'
    search_form_class = PostSearchForm
    context_object_name = 'posts'

    def get_queryset(self):
        qs = super().get_queryset()
        self.search_form = self.search_form_class(self.request.GET)
        return self.search_form.search()

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['search_form'] = self.search_form
        return ctx

templates/base.html
{% load staticfiles %}

<html lang="en" class="mdl-js"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Blog{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
     <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
  <style></style></head>

  <body style="">
    {% block header %}
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'main:main' %}">Blog</a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    {% if request.user.is_authenticated %}
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'main:main' %}">Home</a></li>
                        <li><a href="{% url 'blog:post_create' %}">Post create</a></li>
                    </ul>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="#">{{ request.user.email }}</a></li>
                            <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                        </ul>
                    {% else %}
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="{% url 'login' %}">Sign In</a></li>
                            <li><a href="{% url 'signup' %}">Sign Up</a></li>
                        </ul>
                    {% endif %}
                </div>
            </div>
        </nav>
    {% endblock %}


    <div class="container">
        {% block content %}
        {% endblock %}
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    {% block add_scripts %}
    
    {% endblock %}
</body>
</html>

templates/main.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
    <div class="row">
        <form class=" col-xs-12 form-inline" method="get" action=".">
            {% for field in search_form %}
                {% render_field field class="form-control" %}
            {% endfor %}
            <button type="submit" class="btn btn-default">Search</button>
        </form>
    </div>
    <div class="row">
        {% for post in posts %}
            {% include 'blog/partials/post_preview.html' %}
        {% empty %}
            <div>Doesn't find any posts</div>
        {% endfor %}
    </div>

    {% if is_paginated %}
        {% include 'partials/pagination.html' %}
    {% endif %}
{% endblock %}

{% block add_scripts %}
    <script type="text/javascript">
{% endblock %}